pipelines:
    - name: "first"
      generator: 
        type: linear
        config:
            rate_ms: 1000
            coeff: 0.1
            min: 0
            max: 100
      transforms:
        - type: none
          config:
        - type: noise
          config:
            coeff: 0
            min: 0
            max: 10
      sinks:
        - type: simple
          config:
        - type: dataservice
          config:
        
