pipelines:
    - name: "first"
      generator: 
        type: linear
        config:
            rate_ms: 1
            coeff: 0.0
            min: 0
            max: 1
      transforms:
        - type: noise
          config:
            coeff: 0.0
            min: 0
            max: 10
        - type: none
          config: ''
      sinks:
        - type: simple
          config: '' 
