pipelines:
    - name: "first"
      generator: 
        type: linear
        config:
            rate_ms: 1000000000
            coeff: 0.1
            max: 100
            min: 0
      transform:
        type: noise
        config:
          coeff: 0
          min: 0
          max: 10
      publisher:
        type: simple
        config:
